services:
  app:
    build:
      dockerfile: backend/Dockerfile
    container_name: GreenCodeApp
    environment:
      POSTGRES_CONN: "postgres://postgres:postgres@db:5432/GreenCode"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: GreenCode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d GreenCode
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
  app: